name: repro

on: [push, workflow_dispatch]

env:
  STABLE_PYTHON_VERSION: "3.12"
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Reproduce PyArrow Build Failure on MacOS 13 Runner
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        python-version: ['3.12']

    steps:
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Ensure Latest Pip
        run: python -m pip install --upgrade pip

      - name: Install Arrow
        run: brew install apache-arrow

      - name: Install Build Prerequisites
        run: |
          echo "On newer python pkg_resources is vendored by setuptools."
          pip install Cython==0.29.36 numpy setuptools

      - name: Install PyArrow (With Patch)
        run: |
          git clone https://github.com/DylanLukes/arrow.git
          cd arrow/python
          git checkout gh-38391-on-13.0.0
          python setup.py bdist

      # - name: Install PyArrow (Without Patch)
      #   run: pip install pyarrow==13.0.0
